# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(default='', max_length=200)),
                ('download_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offline_storage.Album')),
            ],
        ),
    ]
